INTERVAL_SECONDS = 60
FIXTURE_SYNC_SECONDS = 6 * 60 * 60
FIXTURE_SYNC_TYPE = "fixtures_today_by_date"
SCHEDULED_STATUSES = {"NS", "TBD"}
FINISHED_STATUSES = {"FT", "AET", "PEN"}
VOID_STATUSES = {"PST", "CANC", "ABD", "AWD", "WO"}
